version: "3"
services: 
    react-app:
        image: react-app-production
        # build: ./client/
        restart: unless-stopped
        stdin_open: true
        ports:
            - "80:80"
            - "443:443"
        networks:
            - mern-app
            # static-network:
            #     ipv4_address: 172.20.128.3
    api-server:
        image: api-server-production
        # build: ./server/
        restart: unless-stopped
        ports: 
            - "5005:5005"
        networks:
            - mern-app
            # static-network:
            #     ipv4_address: 172.20.128.2

networks:
    mern-app:
        driver: bridge
    # static-network:
    #     ipam:
    #         config:
    #             - subnet: 172.20.0.0/16