version: "3"
services: 
    react-app:
        image: heaven28/notes-react-app:latest
        stdin_open: true
        ports:
            - "3000:3000"
        networks:
            - mern-app
        container_name: frontend
        links: 
            - "api-server:api-server"

    api-server:
        image: heaven28/notes-api-server:latest
        ports: 
            - "5005:5005"
        networks:
            - mern-app
        container_name: backend
            

networks:
    mern-app:
        driver: bridge